export default {
  LIST_ROOMS_RESULT: 'LIST_ROOMS_RESULT',
  LIST_FAVORITES_RESULT: 'LIST_FAVORITES_RESULT',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  TOGGLE_FAVORITE_RESULT: 'TOGGLE_FAVORITE_RESULT',
  CREATE_ROOM: 'CREATE_ROOM',
  CREATE_ROOM_RESULT: 'CREATE_ROOM_RESULT',
  SEARCH: 'SEARCH',
  SEARCH_RESULT: 'SEARCH_RESULT',
  SEND_MESSAGE: 'SEND_MESSAGE',
};
